settings:
  type: config_object
  label: 'OCS AI Settings'
  mapping:
    clients:
      type: sequence
      label: 'AI Clients'
      sequence:
        type: mapping
        label: 'AI Client'
        mapping:
          client_id:
            type: string
            label: 'Client Identifier'
          api_key:
            type: string
            label: 'API Key'
          endpoint:
            type: string
            label: 'API Endpoint'
    default_client:
      type: string
      label: 'Default Client ID'
